// Compiled proportional bitmap fonts (generated by tools/fontgen.py).
#pragma once

#include <cstdint>

namespace badge {

struct Glyph {
  uint16_t codepoint;
  uint8_t w, h;       // bitmap size
  int8_t x_off;       // left bearing from pen position
  int8_t y_off;       // top of bitmap relative to the line top (ascent line)
  uint8_t advance;    // pen advance in pixels
  uint8_t reserved;
  uint32_t offset;    // byte offset into Font::bitmap (row-major, MSB first)
};

struct Font {
  const char *name;
  uint8_t line_height;  // ascent + descent (+ line gap)
  uint8_t ascent;       // baseline distance from the line top
  uint8_t descent;
  uint8_t cap_height;
  uint16_t glyph_count;
  const Glyph *glyphs;  // sorted by codepoint
  const uint8_t *bitmap;
  uint32_t bitmap_size;
  uint32_t crc;         // CRC32 over glyph table + bitmap, checked by self-test
};

const Glyph *find_glyph(const Font &f, uint32_t cp);

namespace fonts {
// Generated in firmware/generated/fonts.cpp
extern const Font sans_bold_24;
extern const Font sans_bold_20;
extern const Font sans_bold_17;
extern const Font sans_bold_14;
extern const Font sans_bold_12;
extern const Font sans_12;
extern const Font sans_11;
extern const Font sans_10;
extern const Font sans_bold_10;
extern const Font *const all[];
extern const int count;
}  // namespace fonts

uint32_t font_compute_crc(const Font &f);

}  // namespace badge
