// Small monochrome icons (generated by tools/iconsgen.py from third_party/simple-icons).
#pragma once

#include <cstdint>

namespace badge {

struct Icon {
  uint8_t w, h, stride;
  const uint8_t *bits;  // row-major, MSB first, 1 = ink
};

namespace icons {
extern const Icon github;
extern const Icon discord;
}  // namespace icons

}  // namespace badge
