#!/usr/bin/env python3
"""Compile a profile JSON into firmware defaults (C++ key/value table)."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import badge_profile as prof  # noqa: E402


def c_string(s: str) -> str:
    out = []
    for b in s.encode("utf-8"):
        if b in (0x22, 0x5C):
            out.append("\\" + chr(b))
        elif b == 0x0A:
            out.append("\\n")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append(f"\\{b:03o}")  # octal escapes cannot swallow following hex digits
    return '"' + "".join(out) + '"'


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("profile", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--dump-limits", action="store_true", help="print the Python field table and exit")
    args = ap.parse_args(argv)
    try:
        pairs = prof.load(args.profile)
    except (prof.ProfileError, ValueError) as e:
        print(f"profilegen: {args.profile}: {e}", file=sys.stderr)
        return 1
    lines = [
        "// GENERATED by tools/profilegen.py - do not edit.",
        f"// Source: {args.profile.name}",
        "#include <cstddef>",
        "namespace badge {",
        "struct DefaultEntry { const char *key; const char *value; };",
        "extern const DefaultEntry kDefaultProfile[];",
        "extern const size_t kDefaultProfileCount;",
        "const DefaultEntry kDefaultProfile[] = {",
    ]
    lines += [f"  {{{c_string(k)}, {c_string(v)}}}," for k, v in pairs]
    lines += ["};", f"const size_t kDefaultProfileCount = {len(pairs)};", "}  // namespace badge", ""]
    text = "\n".join(lines)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if not args.out.exists() or args.out.read_text() != text:
        args.out.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
